def load_all_spells():
    return [
        "Abi-Dalzim's Horrid Wilting",
        "Absorb Elements",
      # "Acid Splash",
        "Aganazzar's Scorcher",
      # "Aid",
      # "Alarm",
      # "Alter Self",
      # "Animal Friendship",
      # "Animal Messenger",

      # "Animal Shapes",
      # "Animate Dead",
        # "Animate Objects",
      # "Antilife Shell",
        "Antimagic Field",
        "Antipathy/Sympathy",
      # "Arcane Eye",
        "Arcane Gate",
      # "Arcane Lock",

        "Armor of Agathys",
        "Arms of Hadar",
        "Astral Projection",
      # "Augury",
        "Aura of Life",
        "Aura of Purity",
        "Aura of Vitality",
      # "Awaken",
      # "Bane",

        "Banishing Smite",
        "Banishment",
      # "Barkskin",
      # "Beacon of Hope",
        "Beast Bond",
        "Beast Sense",
      # "Bestow Curse",
        "Bigby's Hand",
      # "Blade Barrier",

        "Blade Ward",
      # "Bless",
      # "Blight",
        "Blinding Smite",
      # "Blindness/Deafness",
      # "Blink",
      # "Blur",
        "Bones of the Earth",
        "Branding Smite",

      # "Burning Hands",
        # "Call Lightning",
      # "Calm Emotions",
        "Catapult",
        "Catnap",
        "Cause Fear",
        "Ceremony",
        "Chain Lightning",
        "Chaos Bolt",

        "Charm Monster",
      # "Charm Person",
      # "Chill Touch",
        "Chromatic Orb",
        "Circle of Death",
        "Circle of Power",
        "Clairvoyance",
        "Clone",
        "Cloud of Daggers",

      # "Cloudkill",
        # "Color Spray",
      # "Command",
        # "Commune with Nature",
        # "Commune",
      # "Compelled Duel",
      # "Comprehend Languages",
        # "Compulsion",
      # "Cone of Cold",

      # "Confusion",
      # "Conjure Animals",
        "Conjure Barrage",
        "Conjure Celestial",
        "Conjure Elemental",
        "Conjure Fey",
        "Conjure Minor Elementals",
        "Conjure Volley",
        "Conjure Woodland Beings",

        # "Contact Other Plane",
        "Contagion",
        "Contingency",
      # "Continual Flame",
        "Control Flames",
        "Control Flames",
        "Control Water",
        "Control Weather",
        "Cordon of Arrows",

        "Counterspell",
        "Create Bonfire",
        "Create Bonfire",
        "Create Food and Water",
        "Create Homunculus",
        "Create or Destroy Water",
        "Create Undead",
        "Creation",
        "Crown of Madness",

        "Crown of Stars",
        "Crusader's Mantle",
      # "Cure Wounds",
      # "Dancing Lights",
        "Danse Macabre",
      # "Darkness",
      # "Darkvision",
        "Dawn",
        "Daylight",

      # "Death Ward",
        "Delayed Blast Fireball",
        "Demiplane",
        "Destructive Wave",
      # "Detect Evil and Good",
      # "Detect Magic",
      # "Detect Poison and Disease",
        "Detect Thoughts",
        "Dimension Door",

        "Disguise Self",
        "Disintegrate",
      # "Dispel Evil and Good",
      # "Dispel Magic",
        "Dissonant Whispers",
        "Divination",
      # "Divine Favor",
        "Divine Word",
        "Dominate Beast",

        "Dominate Monster",
        "Dominate Person",
        "Dragon's Breath",
        "Drawmij's Instant Summons",
        "Dream",
        "Druid Grove",
        "Druidcraft",
        "Dust Devil",
        "Earth Tremor",

        "Earthbind",
        "Earthquake",
      # "Eldritch Blast",
        "Elemental Bane",
        "Elemental Weapon",
        "Enemies Abound",
        "Enervation",
        "Enhance Ability",
      # "Enlarge/Reduce",

        # "Ensnaring Strike",
      # "Entangle",
      # "Enthrall",
        "Erupting Earth",
        "Etherealness",
      # "Evard's Black Tentacles",
      # "Expeditious Retreat",
      # "Eyebite",
      # "Fabricate",

      # "Faerie Fire",
      # "False Life",
        "Far Step",
        "Fear",
      # "Feather Fall",
        "Feeblemind",
        "Feign Death",
        "Find Familiar",
        "Find Greater Steed",

        "Find Steed",
        "Find the Path",
      # "Find Traps",
      # "Finger of Death",
      # "Fire Bolt",
        "Fire Shield",
        "Fire Storm",
      # "Fireball",
        "Flame Arrows",

      # "Flame Blade",
        "Flame Strike",
        "Flaming Sphere",
        "Flesh to Stone",
        "Fly",
      # "Fog Cloud",
        "Forbiddance",
        "Forcecage",
        "Foresight",

      # "Freedom of Movement",
      # "Friends",
        "Frostbite",
        "Frostbite",
        "Gaseous Form",
        "Gate",
      # "Geas",
      # "Gentle Repose",
        "Giant Insect",

        # "Glibness",
        "Globe of Invulnerability",
        "Glyph of Warding",
        "Goodberry",
        "Grasping Vine",
      # "Grease",
      # "Greater Invisibility",
      # "Greater Restoration",
        "Guardian of Faith",

        "Guardian of Nature",
        "Guards and Wards",
      # "Guidance",
      # "Guiding Bolt",
      # "Gust of Wind",
        "Gust",
      # "Hail of Thorns",
        "Hallow",
        "Hallucinatory Terrain",

        # "Harm",
        "Haste",
        "Heal",
        "Healing Spirit",
      # "Healing Word",
      # "Heat Metal",
        "Hellish Rebuke",
        "Heroes' Feast",
      # "Heroism",

      # "Hex",
      # "Hold Monster",
      # "Hold Person",
        "Holy Aura",
        "Holy Weapon",
        "Hunger of Hadar",
      # "Hunter's Mark",
        "Hypnotic Pattern",
        "Ice Knife",

      # "Ice Storm",
      # "Identify",
        "Illusory Dragon",
      # "Illusory Script",
        "Immolation",
        "Imprisonment",
        "Incendiary Cloud",
        "Infernal Calling",
        "Infestation",

      # "Inflict Wounds",
        "Insect Plague",
        "Investiture of Flame",
        "Investiture of Ice",
        "Investiture of Stone",
        "Investiture of Wind",
        "Invisibility",
        "Invulnerability",
      # "Jump",

      # "Knock",
        "Legend Lore",
        "Leomund's Secret Chest",
        "Leomund's Tiny Hut",
      # "Lesser Restoration",
      # "Levitate",
        "Life Transference",
      # "Light",
        "Lightning Arrow",

      # "Lightning Bolt",
      # "Locate Animals or Plants",
        "Locate Creature",
      # "Locate Object",
      # "Longstrider",
        "Maddening Darkness",
        "Maelstrom",
      # "Mage Armor",
      # "Mage Hand",

        "Magic Circle",
        "Magic Jar",
      # "Magic Missile",
        "Magic Mouth",
        "Magic Stone",
      # "Magic Weapon",
      # "Major Image",
        "Mass Cure Wounds",
        "Mass Heal",

        # "Mass Healing Word",
        "Mass Polymorph",
        "Mass Suggestion",
        "Maximilian's Earthen Grasp",
        "Maze",
        "Meld into Stone",
        "Melf's Acid Arrow",
        "Melf's Minute Meteors",
      # "Mending",

        "Mental Prison",
      # "Message",
        "Meteor Swarm",
        "Mighty Fortress",
        "Mind Blank",
        "Mind Spike",
      # "Minor Illusion",
        "Mirage Arcane",
      # "Mirror Image",

        # "Mislead",
      # "Misty Step",
        "Modify Memory",
        "Mold Earth",
        "Moonbeam",
        "Mordenkainen's Faithful Hound",
        "Mordenkainen's Magnificent Mansion",
        "Mordenkainen's Private Sanctum",
        "Mordenkainen's Sword",

        "Move Earth",
        "Negative Energy Flood",
        "Nondetection",
        "Nystul's Magic Aura",
        "Otiluke's Freezing Sphere",
        "Otiluke's Resilient Sphere",
        "Otto's Irresistible Dance",
        "Pass without Trace",
        "Passwall",

        "Phantasmal Force",
      # "Phantasmal Killer",
        "Phantom Steed",
        "Planar Ally",
        "Planar Binding",
      # "Plane Shift",
        "Plant Growth",
        "Poison Spray",
      # "Polymorph",

        "Power Word Heal",
        "Power Word Kill",
        "Power Word Pain",
      # "Power Word Stun",
        "Prayer of Healing",
      # "Prestidigitation",
        "Primal Savagery",
        "Primordial Ward",
        "Prismatic Spray",

        "Prismatic Wall",
      # "Produce Flame",
        "Programmed Illusion",
        "Project Image",
        "Protection from Energy",
        "Protection from Evil and Good",
      # "Protection from Poison",
        "Psychic Scream",
      # "Purify Food and Drink",

        "Pyrotechnics",
        "Raise Dead",
        "Rary's Telepathic Bond",
      # "Ray of Enfeeblement",
      # "Ray of Frost",
        "Ray of Sickness",
        "Regenerate",
        "Reincarnate",
      # "Remove Curse",

      # "Resistance",
        "Resurrection",
        "Reverse Gravity",
        "Revivify",
        "Rope Trick",
      # "Sacred Flame",
      # "Sanctuary",
        "Scatter",
        "Scorching Ray",

        "Scrying",
      # "Searing Smite",
        "See Invisibility",
        "Seeming",
        "Sending",
        "Sequester",
        "Shadow Blade",
        "Shadow of Moil",
        "Shapechange",

        "Shatter",
      # "Shield of Faith",
      # "Shield",
      # "Shillelagh",
      # "Shocking Grasp",
        "Sickening Radiance",
      # "Silence",
        "Silent Image",
        "Simulacrum",

        "Skill Empowerment",
        "Skywrite",
      # "Sleep",
        "Sleet Storm",
        "Slow",
        "Snare",
        "Snilloc's Snowball Swarm",
        "Soul Cage",
        "Spare the Dying",

      # "Speak with Animals",
      # "Speak with Dead",
        "Speak with Plants",
        "Spider Climb",
      # "Spike Growth",
        "Spirit Guardians",
      # "Spiritual Weapon",
        "Staggering Smite",
        "Steel Wind Strike",

        # "Stinking Cloud",
        "Stone Shape",
      # "Stoneskin",
        "Storm of Vengeance",
        "Storm Sphere",
      # "Suggestion",
        "Summon Greater Demon",
        "Summon Lesser Demons",
        "Sunbeam",

        # "Sunburst",
        "Swift Quiver",
        "Symbol",
        "Synaptic Static",
        "Tasha's Hideous Laughter",
        "Telekinesis",
        "Telepathy",
        "Teleport",
        "Teleportation Circle",

        "Temple of the Gods",
        "Tenser's Floating Disk",
        "Tenser's Transformation",
      # "Thaumaturgy",
      # "Thorn Whip",
        "Thunder Step",
        "Thunderclap",
      # "Thunderous Smite",
      # "Thunderwave",

        "Tidal Wave",
        "Time Stop",
        "Tiny Servant",
        "Toll the Dead",
        "Tongues",
        "Transmute Rock",
        "Transport via Plants",
        "Tree Stride",
        "True Polymorph",

        # "True Resurrection",
      # "True Seeing",
        "True Strike",
        "Tsunami",
        "Unseen Servant",
        "Vampiric Touch",
        "Vicious Mockery",
        "Vitriolic Sphere",
        "Wall of Fire",

        "Wall of Force",
        "Wall of Ice",
        "Wall of Light",
        "Wall of Sand",
        "Wall of Stone",
        "Wall of Thorns",
        "Wall of Water",
        "Warding Bond",
        "Warding Wind",

        "Water Breathing",
        "Water Walk",
        "Watery Sphere",
      # "Web",
        "Weird",
        "Whirlwind",
        "Wind Walk",
        "Wind Wall",
        "Wish",

      # "Witch Bolt",
        "Word of Radiance",
        "Word of Recall",
        "Wrath of Nature",
      # "Wrathful Smite",
        "Zephyr Strike",
        "Zone of Truth",
    ]

def long_spells():
    return [
        "Animate Objects",
        "Antimagic Field",
        "Antipathy/Sympathy",
      # "Arcane Gate",
      # "Armor of Agathys",
      # "Arms of Hadar",
        "Astral Projection",
      # "Aura of Life",
      # "Aura of Purity",
      # "Aura of Vitality",
      # "Banishing Smite",
      # "Banishment",
      # "Beast Sense",
      # "Bigby's Hand",
      # "Blade Ward",
      # "Blinding Smite",
      # "Branding Smite",
      # "Call Lightning",
      # "Chain Lightning",
      # "Chromatic Orb",
      # "Circle of Death",
      # "Circle of Power",
      # "Clairvoyance",
      # "Clone",
      # "Cloud of Daggers",
      # "Color Spray",
      # "Commune",
      # "Commune with Nature",
      # "Compulsion",
      # "Conjure Barrage",
      # "Conjure Celestial",
      # "Conjure Elemental",
      # "Conjure Fey",
      # "Conjure Minor Elementals",
      # "Conjure Volley",
      # "Conjure Woodland Beings",
      # "Contact Other Plane",
      # "Contagion",
      # "Contingency",
      # "Control Water",
      # "Control Weather",
      # "Cordon of Arrows",
      # "Counterspell",
      # "Create Food and Water",
      # "Create or Destroy Water",
      # "Create Undead",
      # "Creation",
      # "Crown of Madness",
      # "Crusader's Mantle",
      # "Daylight",
      # "Delayed Blast Fireball",
      # "Demiplane",
      # "Destructive Wave",
      # "Detect Thoughts",
      # "Dimension Door",
      # "Disguise Self",
      # "Disintegrate",
      # "Dissonant Whispers",
      # "Divination",
      # "Divine Word",
      # "Dominate Beast",
      # "Dominate Monster",
      # "Dominate Person",
      # "Drawmij's Instant Summons",
      # "Dream",
      # "Druidcraft",
      # "Earthquake",
      # "Elemental Weapon",
      # "Enhance Ability",
      # "Ensnaring Strike",
      # "Etherealness",
      # "Fabricate",
      # "Fear",
      # "Feeblemind",
      # "Feign Death",
      # "Find Familiar",
      # "Find Steed",
      # "Find the Path",
      # "Fire Shield",
      # "Fire Storm",
      # "Flame Strike",
      # "Flaming Sphere",
      # "Flesh to Stone",
      # "Fly",
      # "Forbiddance",
      # "Forcecage",
      # "Foresight",
      # "Friends",
      # "Gaseous Form",
      # "Gate",
      # "Giant Insect",
      # "Glibness",
      # "Globe of Invulnerability",
      # "Glyph of Warding",
      # "Goodberry",
      # "Grasping Vine",
      # "Guardian of Faith",
      # "Guards and Wards",
      # "Hallow",
      # "Hallucinatory Terrain",
      # "Harm",
      # "Haste",
      # "Heal",
      # "Hellish Rebuke",
      # "Heroes' Feast",
      # "Hex",
      # "Hold Monster",
      # "Holy Aura",
      # "Hunger of Hadar",
      # "Hypnotic Pattern",
      # "Imprisonment",
      # "Incendiary Cloud",
      # "Insect Plague",
      # "Invisibility",
      # "Legend Lore",
      # "Leomund's Secret Chest",
      # "Leomund's Tiny Hut",
      # "Lightning Arrow",
      # "Locate Creature",
      # "Magic Circle",
      # "Magic Jar",
      # "Magic Mouth",
      # "Mass Cure Wounds",
      # "Mass Heal",
      # "Mass Healing Word",
      # "Mass Suggestion",
      # "Maze",
      # "Meld into Stone",
      # "Melf's Acid Arrow",
      # "Meteor Swarm",
      # "Mind Blank",
      # "Mirage Arcane",
      # "Mislead",
      # "Modify Memory",
      # "Moonbeam",
      # "Mordenkainen's Faithful Hound",
      # "Mordenkainen's Magnificent Mansion",
      # "Mordenkainen's Private Sanctum",
      # "Mordenkainen's Sword",
      # "Move Earth",
      # "Nondetection",
      # "Nystul's Magic Aura",
      # "Otiluke's Freezing Sphere",
      # "Otiluke's Resilient Sphere",
      # "Otto's Irresistible Dance",
      # "Pass without Trace",
      # "Passwall",
      # "Phantasmal Force",
      # "Phantom Steed",
      # "Planar Ally",
      # "Planar Binding",
      # "Plant Growth",
      # "Poison Spray",
      # "Power Word Heal",
      # "Power Word Kill",
      # "Prayer of Healing",
      # "Prismatic Spray",
      # "Prismatic Wall",
      # "Programmed Illusion",
      # "Project Image",
      # "Protection from Energy",
      # "Protection from Evil and Good",
      # "Raise Dead",
      # "Rary's Telepathic Bond",
      # "Ray of Sickness",
      # "Regenerate",
      # "Reincarnate",
      # "Resurrection",
      # "Reverse Gravity",
      # "Revivify",
      # "Rope Trick",
      # "Scorching Ray",
      # "Scrying",
      # "See Invisibility",
      # "Seeming",
      # "Sending",
      # "Sequester",
      # "Shapechange",
      # "Shatter",
      # "Silent Image",
      # "Simulacrum",
      # "Sleet Storm",
      # "Slow",
      # "Spare the Dying",
      # "Speak with Plants",
      # "Spider Climb",
      # "Spirit Guardians",
      # "Staggering Smite",
      # "Stinking Cloud",
      # "Stone Shape",
      # "Storm of Vengeance",
      # "Sunbeam",
      # "Sunburst",
      # "Swift Quiver",
      # "Symbol",
      # "Tasha's Hideous Laughter",
      # "Telekinesis",
      # "Telepathy",
      # "Teleport",
      # "Teleportation Circle",
      # "Tenser's Floating Disk",
      # "Thorn Whip",
      # "Time Stop",
      # "Tongues",
      # "Transport via Plants",
      # "Tree Stride",
      # "True Polymorph",
      # "True Resurrection",
      # "True Strike",
      # "Tsunami",
      # "Unseen Servant",
      # "Vampiric Touch",
      # "Vicious Mockery",
      # "Wall of Fire",
      # "Wall of Force",
      # "Wall of Ice",
      # "Wall of Stone",
      # "Wall of Thorns",
      # "Warding Bond",
      # "Water Breathing",
      # "Water Walk",
      # "Weird",
      # "Wind Walk",
      # "Wind Wall",
      # "Wish",
      # "Word of Recall",
      # "Zone of Truth",
    ]